### ISSUE TITLE
Fehler vom Schlagwortfeld nach dem speichern

### ISSUE THREAD

**Issue by srhinow** [heimrichhannot/contao-news-bundle#2]
Zum testen wie dieses Modul mit der codefog/contao-tag Erweiterung umgeht und dieses einbindet, habe ich diese Erweiterung "heimrichhannot/contao-news-bundle" in ner Contao 4.9.10 installiert und die DB aktualisiert. Nach dem anlegen einer test-News und dem abspeichern kam ein Fehler:
![Bildschirmfoto zu 2021-01-03 21-38-28](https://user-images.githubusercontent.com/741418/103488413-96b5c100-4e0c-11eb-9084-bd2c525fc1ec.png)

**Comment by Defcon0** [comment]
Das liegt vermutlich daran, dass der Service nicht als `public: true` gekennzeichnet ist. Kannst du das mal versuchen in der Datei src/Resources/config/listener.yml am entsprechenden Service?

**Comment by srhinow** [comment]
Nein die Erweiterung habe ich dann im Anschluss wieder gelöscht und eine andere genommen.
